### ISSUE TITLE
Failure to Highlight Attribute Value

### ISSUE THREAD

**Issue by alacercogitatus** [yorokobi/vim-splunk#7]
Hi! Whilst working within [searchbnf.conf](https://docs.splunk.com/Documentation/Splunk/6.5.0/Admin/Searchbnfconf), I found that the "example1" or "comment1" attributes don't highlight correctly.

![screen shot 2016-10-17 at 3 15 12 pm](https://cloud.githubusercontent.com/assets/7861056/19457737/88df51ca-947c-11e6-9bdf-8208c4186e64.png)

**Comment by yorokobi** [comment]
See commit dab7c4e801142ce44b9b471868ce421f38e839fd
