### ISSUE TITLE
No Rules for checklist.conf

### ISSUE THREAD

**Issue by alacercogitatus** [yorokobi/vim-splunk#8]
New configuration file for 6.5 [checklist.conf](https://docs.splunk.com/Documentation/Splunk/6.5.0/Admin/Checklistconf) is not supported by VIM Syntax.

**Comment by yorokobi** [comment]
Also missing from etc/apps/splunk_monitoring_console/README/ 

dmc_alerts.conf
splunk_monitoring_console_assets.conf

**Comment by alacercogitatus** [comment]
Yes, but I have it on Great Authority, don't touch those :D

**Comment by yorokobi** [comment]
See commit 0d725d5a622f6770a1aeda6c372fe06dbcd73c8e
